let mode = "development"

const MiniCssExtractPlugin = require('mini-css-extract-plugin');

if(process.env.NODE_ENV === "production") {
    mode = "production"
}

module.exports = {
    mode,
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader'
                }
            }, {
                test: /\.s?css$/i,
                use: [MiniCssExtractPlugin.loader, "css-loader", "postcss-loader", "sass-loader"]
                /*
                * right - left
                * css-loader -> collect all the css files referenced in your application and put it into a string
                * style-loader/MiniCssExtractPlugin -> would take a output string generated by css-loader and put it inside <style> tag
                * diff btw style-loader & MiniCssExtractPlugin
                *   style-loader will inject styles in a js bundle,
                *   MiniCssExtractPlugin will create a separate css file
                * postcss -> add vendor prefixes to css rules
                * */
            }
        ],
    },

    plugins: [new MiniCssExtractPlugin()],


    devtool: "source-map", //enable source-map dev-tools
    devServer: {
        contentBase: "./dist", // to render index.html directly instead of folder structure
        hot: true, // enable hot-reloading instead of live reloading
    }
}
