const LOGIN_ACTIONS_TYPE = {
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    SET_USERNAME: 'SET_USERNAME',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_USER_AUTHENTICATED: 'SET_USER_AUTHENTICATED',
}

const HOME_ACTIONS_TYPE = {
    FETCH_ALL_USERS: 'FETCH_ALL_USERS',
    SET_USERS_DATA: 'SET_USERS_DATA',
    ADD_NEW_USER: 'ADD_NEW_USER',
}

export {
    LOGIN_ACTIONS_TYPE,
    HOME_ACTIONS_TYPE,
}
